export const EMOJI_TO_CALLOUT_KIND: Record<string, string> = {
  "📘": "info",
  "ℹ️": "info",
  "📝": "info",
  "💡": "info",
  "📗": "success",
  "👍": "tip",
  "✅": "success",
  "⚠️": "alert",
  "🚧": "alert",
  "❗": "danger",
  "❗️": "danger",
  "🛑": "danger",
  "❌": "danger",
  "📙": "alert",
  "📕": "danger",
};

export const CALLOUT_EMOJIS = Object.keys(EMOJI_TO_CALLOUT_KIND);

export const KIND_MAP: Record<string, string> = {
  info: "info",
  default: "info",
  note: "info",
  success: "success",
  okay: "success",
  tip: "tip",
  warning: "alert",
  warn: "alert",
  caution: "alert",
  danger: "danger",
  error: "danger",
  critical: "danger",
};

export const COMPONENT_RENAME: Record<string, string> = {
  Accordion: "Expandable",
  AccordionGroup: "ExpandableGroup",
};

export const FA_TO_LUCIDE: Record<string, string> = {
  "fa-rocket": "rocket",
  "fa-check": "check",
  "fa-check-circle": "check-circle",
  "fa-info-circle": "info",
  "fa-info": "info",
  "fa-warning": "triangle-alert",
  "fa-exclamation-triangle": "alert-triangle",
  "fa-exclamation-circle": "alert-circle",
  "fa-exclamation": "alert-triangle",
  "fa-times": "x",
  "fa-times-circle": "x-circle",
  "fa-star": "star",
  "fa-heart": "heart",
  "fa-cog": "settings",
  "fa-cogs": "settings",
  "fa-gear": "settings",
  "fa-search": "search",
  "fa-user": "user",
  "fa-users": "users",
  "fa-lock": "lock",
  "fa-unlock": "unlock",
  "fa-key": "key",
  "fa-code": "code",
  "fa-terminal": "terminal",
  "fa-file": "file",
  "fa-file-text": "file-text",
  "fa-folder": "folder",
  "fa-download": "download",
  "fa-upload": "upload",
  "fa-link": "link",
  "fa-external-link": "external-link",
  "fa-globe": "globe",
  "fa-database": "database",
  "fa-server": "server",
  "fa-cloud": "cloud",
  "fa-bolt": "zap",
  "fa-lightning": "zap",
  "fa-book": "book-open",
  "fa-bookmark": "bookmark",
  "fa-eye": "eye",
  "fa-eye-slash": "eye-off",
  "fa-edit": "pencil",
  "fa-pencil": "pencil",
  "fa-trash": "trash-2",
  "fa-plus": "plus",
  "fa-minus": "minus",
  "fa-arrow-right": "arrow-right",
  "fa-arrow-left": "arrow-left",
  "fa-chevron-right": "chevron-right",
  "fa-chevron-down": "chevron-down",
  "fa-home": "home",
  "fa-shield": "shield",
  "fa-bell": "bell",
  "fa-envelope": "mail",
  "fa-credit-card": "credit-card",
  "fa-calendar": "calendar",
  "fa-clock": "clock",
  "fa-refresh": "refresh-cw",
  "fa-sync": "refresh-cw",
  "fa-play": "play",
  "fa-pause": "pause",
  "fa-stop": "square",
  "fa-copy": "copy",
  "fa-clipboard": "clipboard",
  "fa-list": "list",
  "fa-table": "table",
  "fa-image": "image",
  "fa-camera": "camera",
  "fa-video": "video",
  "fa-map": "map",
  "fa-flag": "flag",
  "fa-tag": "tag",
  "fa-tags": "tags",
  "fa-wrench": "wrench",
  "fa-magic": "sparkles",
  "fa-lightbulb": "lightbulb",
  "fa-plug": "plug",
  "fa-puzzle-piece": "puzzle",
  "fa-cube": "package",
  "fa-desktop": "monitor",
  "fa-mobile": "smartphone",
  "fa-github": "github",
  "fa-apple": "apple",
  "fa-windows": "monitor",
  "fa-linux": "terminal",
};

export const README_ONLY_FIELDS = new Set([
  "category", "categorySlug", "slug", "order", "type",
  "parentDoc", "parentDocSlug", "childrenPages",
  "hidden", "deprecated",
  "excerpt", "icon", "fullscreen",
  "metadata",
  "link", "link_url", "link_external",
  "api", "isReference",
  "recipe",
  "next", "previous",
  "id", "_id", "version", "updatedAt", "createdAt",
]);

export const CODE_FENCE_LANG_MAP: Record<string, string> = {
  curl: "bash",
  shell: "bash",
  sh: "bash",
  zsh: "bash",
  cmd: "bash",
  powershell: "powershell",
  ps: "powershell",
  ps1: "powershell",
  node: "javascript",
  nodejs: "javascript",
  js: "javascript",
  ts: "typescript",
  py: "python",
  rb: "ruby",
  yml: "yaml",
  htm: "html",
};

export const SAFE_TAGS = new Set([
  "br", "hr", "img", "input", "meta", "link", "source", "area", "base",
  "col", "embed", "wbr",
  "div", "span", "p", "a", "table", "thead", "tbody", "tfoot", "tr", "th",
  "td", "ul", "ol", "li", "pre", "code", "blockquote",
  "h1", "h2", "h3", "h4", "h5", "h6",
  "em", "strong", "del", "sub", "sup", "b", "i", "u", "s", "small", "mark",
  "abbr", "cite", "q", "kbd",
  "details", "summary", "section", "article", "aside", "header", "footer",
  "nav", "main", "figure", "figcaption",
  "iframe", "video", "audio", "svg", "path", "circle", "rect", "line",
  "polyline", "polygon", "g", "dl", "dt", "dd",
  "Callout", "Card", "Columns", "Image", "Video", "Iframe",
  "CodeGroup", "Expandable", "ExpandableGroup",
  "Steps", "Step", "Tabs", "Tab", "Update",
  "ParamField", "ResponseField", "Request", "Response",
  "Frame", "Icon", "Column", "Anchor", "Glossary", "Table", "Embed",
]);

export const CONTAINER_COMPONENTS = new Set([
  "Callout", "Card", "Columns", "Column",
  "Expandable", "ExpandableGroup",
  "Steps", "Step",
  "Tabs", "Tab",
  "CodeGroup", "Update",
]);
